apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-rule-crd.yaml
  - monitoring-base.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - loki-deployment.yaml
  - tempo-deployment.yaml
  - prometheus-rules.yaml

namespace: monitoring
