apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-deployment.yaml
- grafana-deployment.yaml
- tempo-deployment.yaml
- loki-deployment.yaml

namespace: monitoring
