apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dese-frontend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: app.poolfab.com.tr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dese-frontend-service
                port:
                  number: 80

