apiVersion: v1
kind: Service
metadata:
  name: dese-iot-mqtt-service
  labels:
    app: dese-iot-mqtt
spec:
  selector:
    app: dese-iot-mqtt
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 9001
      targetPort: 9001
      name: websockets
  type: ClusterIP

