apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: monitoring

patchesStrategicMerge:
- seo-observer-patch.yaml

configMapGenerator:
- name: seo-config
  literals:
    - environment=production
    - cluster=desewebv5
    - target-url=https://www.cpt.com.tr
