apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - security-base.yaml
  - kyverno-helm.yaml
  - kyverno-policies.yaml

namespace: kyverno

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
