admissionController:
  replicas: 1
  container:
    resources:
      requests:
        cpu: "20m"
        memory: "96Mi"
      limits:
        cpu: "80m"
        memory: "192Mi"

backgroundController:
  replicas: 1
  resources:
    requests:
      cpu: "15m"
      memory: "60Mi"
    limits:
      cpu: "60m"
      memory: "120Mi"

cleanupController:
  replicas: 1
  createSelfSignedCert: true
  resources:
    requests:
      cpu: "10m"
      memory: "60Mi"
    limits:
      cpu: "50m"
      memory: "120Mi"

reportsController:
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "60Mi"
    limits:
      cpu: "50m"
      memory: "120Mi"

crds:
  install: true
