admissionController:
  replicas: 1
  container:
    resources:
      requests:
        cpu: "30m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"

backgroundController:
  replicas: 1
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "80m"
      memory: "128Mi"

cleanupController:
  replicas: 1
  createSelfSignedCert: true
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "80m"
      memory: "128Mi"

reportsController:
  replicas: 1
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "80m"
      memory: "128Mi"

crds:
  install: true
