apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: monitoring

patchesStrategicMerge:
  - prometheus-patch.yaml
  - grafana-patch.yaml

configMapGenerator:
  - name: monitoring-config
    literals:
      - environment=production
      - cluster=desewebv5
