apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: kyverno

patchesStrategicMerge:
- kyverno-policies-patch.yaml

configMapGenerator:
- name: security-config
  literals:
    - environment=production
    - cluster=desewebv5
    - policy-mode=enforce
